name: Daily Node Job

on:
  schedule:
    - cron: "41 09 * * *"   # runs once every day at midnight UTC
  workflow_dispatch:      # optional manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
      PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
      DEPARTURE_STATION: ${{ secrets.DEPARTURE_STATION }}
      ARRIVAL_STATION: ${{ secrets.ARRIVAL_STATION }}
      DEPARTURE_TIME: ${{ secrets.DEPARTURE_TIME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js